eureka:
  instance:
    hostName: localhost
    instanceId: ${spring.application.name}:${random.int}
    # Set it to a value of less than 30 speed up the process of getting clients connected to other service(default 30)
    # In test environment only
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    # Disable Eureka client refresh
    refresh:
      enable: false
